/*
 * Root Layout:
- Charge les styles globaux
- Définit les métadonnées par défaut (Next.js les injecte dans <head>)
 */

import '@/styles/globals.scss';
import type { ReactNode } from 'react';
import type { Metadata } from 'next';

/*-------------------------------------------------*
//* Métadonnées globales
* - Appliquées à toutes les pages par défaut
/*-------------------------------------------------*/
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // Vous pouvez aussi ajouter ici vos keywords, robots, etc.
};

/*-------------------------------------------------*
//* RootLayout
* - Déclare UNE SEULE FOIS <html> et <body>
* - Ne met pas de lang fixe (on utilisera <head> pour le content-language)
/*-------------------------------------------------*/
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return <>{children}</>;
}
