/*
 * Root Layout:
- Charge les styles globaux
- Définit les métadonnées par défaut (Next.js les injecte dans <head>)
- Ne déclare plus <html> ni <body>
 */

import '@/styles/globals.scss';
import type { ReactNode } from 'react';
import type { Metadata } from 'next';

// import { Geist, Geist_Mono } from 'next/font/google';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

//*---------------- 1) Métadonnées globales (appliquées à toutes les pages par défaut) :
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//*---------------- 2) Le layout racine définit UNE seule fois <html> et <body>
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return <>{children}</>;
}
